In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]

In [7]:
a = np.array(a)

In [16]:
np.arange(0,5.0+0.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

In [18]:
np.linspace(0.0,5.0,51)
#np.linspace(start,stop,num el)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
b= np.ones(10,dtype=complex)

In [34]:
b

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [49]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [50]:
a= np.array(a)

In [67]:
b = np.arange(0,2,0.1)

In [73]:
b.reshape(4,5)

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [74]:
b = b.flatten()

In [77]:
b.shape

(20,)

In [78]:
np.zeros?

In [79]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [81]:
c = b*10    

In [84]:
c = np.arange(0,20,1).reshape(4,5)

In [85]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
c[c % 2 == 0]=100

In [95]:
c

array([[100,   1, 100,   3, 100],
       [  5, 100,   7, 100,   9],
       [100,  11, 100,  13, 100],
       [ 15, 100,  17, 100,  19]])

In [96]:
import math

In [100]:
math.exp(1)

2.718281828459045

In [105]:
np.sin(b).reshape(5,-1)

array([[0.        , 0.09983342, 0.19866933, 0.29552021],
       [0.38941834, 0.47942554, 0.56464247, 0.64421769],
       [0.71735609, 0.78332691, 0.84147098, 0.89120736],
       [0.93203909, 0.96355819, 0.98544973, 0.99749499],
       [0.9995736 , 0.99166481, 0.97384763, 0.94630009]])

In [106]:
c

array([[100,   1, 100,   3, 100],
       [  5, 100,   7, 100,   9],
       [100,  11, 100,  13, 100],
       [ 15, 100,  17, 100,  19]])

In [107]:
d = c

In [108]:
d

array([[100,   1, 100,   3, 100],
       [  5, 100,   7, 100,   9],
       [100,  11, 100,  13, 100],
       [ 15, 100,  17, 100,  19]])

In [110]:
d[0,0]= 1000

In [114]:
c is d

True

In [115]:
(c % 2 == 0) + (c % 3 == 0)

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])